const MensClothesesAccesseroies = [
  {
    Id: "01",
    productImage: "Assets/Asset1/TopBrand/01_Nike.png",
    productName: "Niki",
    productDetails: "created for the Lux life",
    currentPrice: 2799,
    originalPrice: 6999,
    Discount: 60,
  },
  {
    Id: "02",
    productImage: "Assets/Asset1/TopBrand/02_levisShos.png",
    productName: "Levis",
    productDetails: "created for the Lux life",
    currentPrice: 2499,
    originalPrice: 9999,
    Discount: 75,
  },
  {
    Id: "03",
    productImage: "Assets/Asset1/TopBrand/03_puma.png",
    productName: "Puma",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "04",
    productImage: "Assets/Asset1/TopBrand/04_poloCap.png",
    productName: "Polo Cap",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "05",
    productImage: "Assets/Asset1/TopBrand/05_skechers.png",
    productName: "Skechers Shoes",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "06",
    productImage: "Assets/Asset1/TopBrand/06_TommyHilfiger.png",
    productName: "Tommy Hilfiger",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "07",
    productImage: "Assets/Asset1/TopBrand/07_crocs.png",
    productName: "Crocs Shoes",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "08",
    productImage: "Assets/Asset1/CatagoryBag/Shirts.png",
    productName: "Shirts",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "09",
    productImage: "Assets/Asset1/CatagoryBag/T-shirts.png",
    productName: "T-Shirts",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "10",
    productImage: "Assets/Asset1/CatagoryBag/Jens.png",
    productName: "Jeans",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "11",
    productImage: "Assets/Asset1/CatagoryBag/ShortsTrousers.png",
    productName: "Shorts & Trousers",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "12",
    productImage: "Assets/Asset1/CatagoryBag/Causal.png",
    productName: "Casual Shoes",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },

  {
    Id: "13",
    productImage: "Assets/Asset1/Lux_Brand/01_Shorts.png",
    productName: "Shorts",
    productDetails: "created for the Lux life",
    currentPrice: 2799,
    originalPrice: 6999,
    Discount: 60,
  },
  {
    Id: "14",
    productImage: "Assets/Asset1/Lux_Brand/02_formal.png",
    productName: "Shorts",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "15",
    productImage: "Assets/Asset1/Lux_Brand/03_Sports.png",
    productName: "Shorts",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "16",
    productImage: "Assets/Asset1/Lux_Brand/04_RolexWatch.png",
    productName: "Shorts",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "17",
    productImage: "Assets/Asset1/Lux_Brand/05_Hugo.png",
    productName: "Shorts",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "18",
    productImage: "Assets/Asset1/Lux_Brand/06_Ducati.png",
    productName: "Shorts",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },

  {
    Id: "19",
    productImage: "Assets/Asset1/IndianWears/01_treditional.png",
    productName: "Kurta",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "20",
    productImage: "Assets/Asset1/IndianWears/02_EthicWear.png",
    productName: "Designer kurta",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "21",
    productImage: "Assets/Asset1/IndianWears/03_Printedkurta.png",
    productName: "Printed kurta",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "22",
    productImage: "Assets/Asset1/IndianWears/04_DailyKurata.png",
    productName: "Kurta",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "23",
    productImage: "Assets/Asset1/IndianWears/05_Dailywear.png",
    productName: "Kurta",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },

  {
    Id: "24",
    productImage: "Assets/Asset1/Sports/01_Shoes.png",
    productName: "shoes",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "25",
    productImage: "Assets/Asset1/Sports/02_Wear.png",
    productName: "sports wear",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "26",
    productImage: "Assets/Asset1/Sports/03_Tshirts.png",
    productName: "Tshirts",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "27",
    productImage: "Assets/Asset1/Sports/04_TshirtsPaints.png",
    productName: "created for the Lux life",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "28",
    productImage: "Assets/Asset1/Sports/05_SCampusChoes.png",
    productName: "created for the Lux life",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },

  {
    Id: "29",
    productImage: "Assets/Asset1/Accessories/01_Headphone.png",
    productName: "created for the Lux life",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "30",
    productImage: "Assets/Asset1/Accessories/02_sportsWatch.png",
    productName: "created for the Lux life",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "31",
    productImage: "Assets/Asset1/Accessories/03_whiteWatch.png",
    productName: "created for the Lux life",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "32",
    productImage: "Assets/Asset1/Accessories/04_fasttrack.png",
    productName: "created for the Lux life",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
  {
    Id: "33",
    productImage: "Assets/Asset1/Accessories/05_minimastic.png",
    productName: "created for the Lux life",
    productDetails: "created for the Lux life",
    currentPrice: 2599,
    originalPrice: 4999,
    Discount: 52,
  },
];
