const Products = [
  {
    Id: "01",
    productImage: "ProductsCartImage/Assets 1.png",
    productName: "Kalini",
    productDetails: "kurta with trousers & dupatta",
    currentPrice: 1748,
    originalPrice: 4995,
    discountPercentage: 65,
    rating: {
      rate: 4.1,
      count: 1.4,
    },
  },
  {
    Id: "02",
    productImage: "ProductsCartImage/Assets 2.png",
    productName: "Indo Era",
    productDetails: "Embroidered Kurta set",
    currentPrice: 1999,
    originalPrice: 7999,
    discountPercentage: 75,
    rating: {
      rate: 4.3,
      count: 3.7,
    },
  },
  {
    Id: "03",
    productImage: "ProductsCartImage/Assets 3.png",
    productName: "Sangria",
    productDetails: "Embroidered A-Line Kurta set",
    currentPrice: 2194,
    originalPrice: 6649,
    discountPercentage: 67,
    rating: {
      rate: 4.1,
      count: 5.5,
    },
  },
  {
    Id: "04",
    productImage: "ProductsCartImage/Assets 4.png",
    productName: "Kalini",
    productDetails: "Anarkali Gotta Patti Kurta set",
    currentPrice: 999,
    originalPrice: 4345,
    discountPercentage: 77,
    rating: {
      rate: 106,
      count: 123,
    },
  },
  {
    Id: "05",
    productImage: "ProductsCartImage/Assets 5.png",
    productDetails: "Embroidered A-Line Kurta set",
    currentPrice: 2194,
    originalPrice: 6649,
    discountPercentage: 67,
    rating: {
      rate: 4.1,
      count: 5.5,
    },
  },
  {
    Id: "06",
    productImage: "ProductsCartImage/Assets 6.png",
    productName: "Anni Designer",
    productDetails: "Kurta with trouser & dupatta",
    currentPrice: 1086,
    originalPrice: 4345,
    discountPercentage: 75,
    rating: {
      rate: 3.2,
      count: 5,
    },
  },
  {
    Id: "07",
    productImage: "ProductsCartImage/Assets 7.png",
    productName: "goSriki",
    productDetails: "printed AnarkaliKurta set",
    currentPrice: 955,
    originalPrice: 4345,
    discountPercentage: 78,
    rating: {
      rate: 3.9,
      count: 1.4,
    },
  },
  {
    Id: "08",
    productImage: "ProductsCartImage/Assets 8.png",
    productName: "goSriki",
    productDetails: "printed straight Kurta set",
    currentPrice: 799,
    originalPrice: 3197,
    discountPercentage: 75,
    rating: {
      rate: 3.1,
      count: 48,
    },
  },
  {
    Id: "09",
    productImage: "ProductsCartImage/Assets 9.png",
    productName: "all about you",
    productDetails: "Embroidered satin saree",
    currentPrice: 1739,
    originalPrice: 5799,
    discountPercentage: 70,
    rating: {
      rate: 4.8,
      count: 6.1,
    },
  },
  {
    Id: "10",
    productImage: "ProductsCartImage/Assets 10.png",
    productName: "kasee",
    productDetails: "breads and stones saree",
    currentPrice: 2148,
    originalPrice: 7163,
    discountPercentage: 70,
    rating: {
      rate: 4.3,
      count: 1.5,
    },
  },
  {
    Id: "11",
    productImage: "ProductsCartImage/Assets 11.png",
    productName: "kalini",
    productDetails: "Anarkali pure cotton kuarta set",
    currentPrice: 1459,
    originalPrice: 7299,
    discountPercentage: 80,
    rating: {
      rate: 4.4,
      count: 14.1,
    },
  },
  {
    Id: "12",
    productImage: "ProductsCartImage/Assets 12.png",
    productName: "Indro Era",
    productDetails: "kurata with trouser & dupatta",
    currentPrice: 1799,
    originalPrice: 5999,
    discountPercentage: 70,
    rating: {
      rate: 4.3,
      count: 5.7,
    },
  },
  {
    Id: "13",
    productImage: "ProductsCartImage/Assets 10.png",
    productName: "kalini",
    productDetails: "Embroidered kurata set",
    currentPrice: 1554,
    originalPrice: 8179,
    discountPercentage: 81,
    rating: {
      rate: 4.0,
      count: 10.5,
    },
  },
  {
    Id: "14",
    productImage: "ProductsCartImage/Assets 14.png",
    productName: "Anaya ",
    productDetails: "kurta with trouser & dupatta",
    currentPrice: 1711,
    originalPrice: 4890,
    discountPercentage: 65,
    rating: {
      rate: 4.3,
      count: 12.8,
    },
  },
  {
    Id: "15",
    productImage: "ProductsCartImage/Assets 15.png",
    productName: "GoSriKi",
    productDetails: "kurta with trouser & dupatta",
    currentPrice: 869,
    originalPrice: 4345,
    discountPercentage: 80,
    rating: {
      rate: 4.1,
      count: 10.7,
    },
  },
];
